apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agenthost.fullname" . }}-secrets
type: Opaque
stringData:
  connectionString: {{ .Values.secrets.connectionString | default (printf "Host=%s-postgres;Database=%s;Username=%s;Password=%s" (include "agenthost.fullname" .) .Values.postgres.auth.database .Values.postgres.auth.username .Values.postgres.auth.password) | quote }}
